collections:
  categories:
    output: true

plugins:
  - jekyll-feed

# Setting front matter defaults
defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"